name: Makefile build

on:
  push:
    tags:
      - 'releases/v*'

    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: (Get metadata)
        id: metadata
        run: |
          source buildscript/buildconfig.sh
          echo "::set-output name=version::$version"
          echo "::set-output name=build::$build"
          echo "::set-output name=package::$package"
          echo "::set-output name=name::$name"
          echo "::set-output name=debug::$debug"

      - name: Install dependencies
        run: sudo apt install zip bzip2 gzip tar curl bash

      - name: Cache build environment downloads
        id: cache-downloads
        uses: actions/cache@v2
        with:
          path: |
            build
            !build/ut-server
          key: ${{ runner.os }}-${{ hashFiles('build/deps/**') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Download build environment
        if: steps.cache-downloads.outputs.cache-hit != 'true'
        run: make download

      - name: Set up build environment
        run: make configure

      - name: Build
        run: make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.metadata.outputs.package }}-distrib-zip
          path: build/dist/${{ steps.metadata.outputs.package }}/latest/*
          if-no-files-found: error

  publish:
    name: Publish Tag Release (if applicable)
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/releases/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: (Get metadata)
        id: metadata
        run: |
          source buildscript/buildconfig.sh
          echo "::set-output name=version::$version"
          echo "::set-output name=build::$build"
          echo "::set-output name=package::$package"
          echo "::set-output name=debug::$debug"
          echo "::set-output name=name::$name"

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ steps.metadata.outputs.package }}-distrib-zip
          path: /tmp/distrib


      - name: Release!
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/distrib/*
          tag_name: releases/v${{ steps.metadata.outputs.version }}
          name: ${{ steps.metadata.outputs.name }} v${{ steps.metadata.outputs.version }}
          body_path: CHANGELOG.md
          draft: true
          prerelease: ${{ steps.metadata.outputs.debug }}
